language: go
go:
- '1.10'
sudo: false
install:
- go get -v github.com/alecthomas/gometalinter
- gometalinter --install
script:
  - export PATH=$PATH:$HOME/gopath/bin
  - export REGISTRY=0x7B25494cF297D63eA2AF72d43Fc133408674c43a
  - export CHANNEL=0x021a641147131481de1be929cd5f2c0c42cc25f40db8ee06d21924e614b49b68
  - export TOKEN_NETWORK_REGISTRY=0x7B25494cF297D63eA2AF72d43Fc133408674c43a
  - export TOKEN_NETWORK=0x06bE91b5DdA5a0459C0FF7Bc016A2D21E276C2e4
  - export KEY1=2ddd679cb0f0754d0e20ef8206ea2210af3b51f159f55cfffbd8550f58daf779
  - export KEY2=36234555bc087435cf52371f9a0139cb98a4267ba62b722e3f46b90d35f31678
  - export ISTEST=1
  - export ETHRPCENDPOINT="ws://182.254.155.208:30306"
  #- go get  ./...
  - chmod +x ./goclean.sh
  - ./goclean.sh
  - go build
  - pwd
  # - pwd
  # - go test -timeout 30m ./...
  - chmod +x ./smoketest.sh
  - ./smoketest.sh

notifications:
  email:
    on_success: never
    on_failure: always
